### ISSUE TITLE
冒昧地问您一下，请问staticman可以用在hexo上吗？

### ISSUE THREAD

**Issue by iloveyz** [zongren/comment#186]
因为十分不熟，所以想先搞清楚hexo是否可用staticman作为评论呢？我看https://github.com/eduardoboucas/staticman
标签只写了我知道的jeklly和hugo没有hexo，而google到您这发现您使用的是hexo，但却没有评论所以才在此地特意询问您一下，如果留言的地方对您造成困扰和不便，还望能够谅解。如果可以还望告之，非常感谢。

**Comment by zongren** [comment]
是可以用的，之所以没有开评论是因为公共的staticman服务没办法处理垃圾回复
